import ingredientsData from "@/src/data/ingredients.json";
import effectsData from "@/src/data/effects.json";
import type { Ingredient, Effect } from "@/src/data/types";
import { PotionMixer } from "@/src/components/PotionMixer";
import { allValidPairs } from "@/src/lib/alchemy";
import { EMPTY_SELECTION, type AlchemySelection } from "@/src/lib/alchemyState";
import type { Metadata } from "next";
import { notFound } from "next/navigation";

// Only render pages generated by generateStaticParams
export const dynamicParams = false;

const ALL_INGREDIENTS = (ingredientsData as Ingredient[]).sort((a, b) =>
  a.name.localeCompare(b.name)
);
const ALL_EFFECTS = (effectsData as Effect[]).sort((a, b) =>
  a.name.localeCompare(b.name)
);

export async function generateStaticParams() {
  const params: { seg: string }[] = [];

  for (const ing of ALL_INGREDIENTS) {
    params.push({ seg: ing.id });
  }

  for (const effect of ALL_EFFECTS) {
    params.push({ seg: effect.id });
  }

  const pairs = allValidPairs(ALL_INGREDIENTS, ALL_EFFECTS);
  for (const pair of pairs) {
    const slug = [...pair]
      .map((i) => i.id)
      .sort()
      .join("+");
    params.push({ seg: slug });
  }

  return params;
}

function parseSegToSelection(seg: string): AlchemySelection {
  const ids = seg.split("+");
  const ingredientIds: string[] = [];
  const effectIds: string[] = [];
  for (const id of ids) {
    if (ALL_INGREDIENTS.some((i) => i.id === id)) {
      ingredientIds.push(id);
    } else if (ALL_EFFECTS.some((e) => e.id === id)) {
      effectIds.push(id);
    }
  }
  return { ingredientIds: ingredientIds.slice(0, 3), effectIds };
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ seg: string }>;
}): Promise<Metadata> {
  const { seg } = await params;
  const sel = parseSegToSelection(seg);

  if (sel.ingredientIds.length === 1 && sel.effectIds.length === 0) {
    const ing = ALL_INGREDIENTS.find((i) => i.id === sel.ingredientIds[0]);
    if (!ing) return {};
    const effectNames = ing.effects
      .map((eid) => ALL_EFFECTS.find((e) => e.id === eid)?.name)
      .filter(Boolean)
      .join(", ");
    return {
      title: `${ing.name} — Skyrim Alchemy`,
      description: `Skyrim alchemy ingredient: ${ing.name}. Alchemical effects: ${effectNames}.`,
    };
  }

  if (sel.ingredientIds.length === 0 && sel.effectIds.length === 1) {
    const effect = ALL_EFFECTS.find((e) => e.id === sel.effectIds[0]);
    if (!effect) return {};
    return {
      title: `${effect.name} — Skyrim Alchemy`,
      description: `Find Skyrim ingredients that produce ${effect.name}. Complete alchemy reference.`,
    };
  }

  const ingNames = sel.ingredientIds
    .map((id) => ALL_INGREDIENTS.find((i) => i.id === id)?.name ?? id)
    .join(" + ");
  return {
    title: `${ingNames} Potion — Skyrim Alchemy`,
    description: `Combine ${ingNames} in Skyrim to craft potions. See shared effects and compatible ingredients.`,
  };
}

export default async function SegPage({
  params,
}: {
  params: Promise<{ seg: string }>;
}) {
  const { seg } = await params;
  const selection = parseSegToSelection(seg);

  if (
    selection.ingredientIds.length === 0 &&
    selection.effectIds.length === 0
  ) {
    notFound();
  }

  return (
    <div className="flex-1 px-4 py-6 max-w-5xl mx-auto w-full">
      <div className="mb-5">
        <h1 className="text-xl font-semibold text-[var(--text)]">Alchemy</h1>
        <p className="text-sm text-[var(--text-muted)] mt-1">
          Select ingredients or effects to find matching potions. Up to 3
          ingredients.
        </p>
      </div>
      <PotionMixer
        ingredients={ALL_INGREDIENTS}
        effects={ALL_EFFECTS}
        initialSelection={selection}
      />
    </div>
  );
}
